const resList = [
    {
      
      data: {
        id: "47589",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.8,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
       deliveryTime: 28,
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shambhus Cafe",
        cloudinaryImageId: "ohhbevxuw3iucwxw3x09",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.3,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shivas Cafe",
        cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.8,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Khichdi wala",
        cloudinaryImageId: "nengejcwr1mhpjjgladx",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.2,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Burger King",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.2,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 2.9,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shivas Cafe",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.5,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Khichdi wala",
        cloudinaryImageId: "b3915967a4dbe11f614fc9f535e53f83",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.9,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Burger King",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.9,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shambhus Cafe",
        cloudinaryImageId: "ohhbevxuw3iucwxw3x09",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shivas Cafe",
        cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Khichdi wala",
        cloudinaryImageId: "nengejcwr1mhpjjgladx",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Burger King",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Shivas Cafe",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Khichdi wala",
        cloudinaryImageId: "b3915967a4dbe11f614fc9f535e53f83",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "Burger King",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "izngkxnhvcxpw0y3dgvt",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      
      data: {
        id: "47589",
        name: "MaC Donald's",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "City Gold Complex",
        areaName: "Navrangpura",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4,
        parentId: "721",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 28,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
  ];

  export default resList;